In [2]:
import pandas as pd
df = pd.read_csv('processed_cars.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None) 
df.head()

,id,Make,Model,Generation,Year_from,Year_to,Series,Trim,Body_type,full_weight_kg,max_trunk_capacity_l,drive_wheels,transmission,cylinder_layout,number_of_cylinders,fuel_type,cylinder_bore_mm,stroke_cycle_mm,capacity_cm3,maximum_torque_n_m,turnover_of_maximum_torque_rpm,engine_hp,engine_hp_rpm,acceleration_0_100_km/h_s,max_speed_km_per_h,number_of_gears,fuel_tank_capacity_l,mixed_fuel_consumption_per_100_km_l,city_fuel_per_100km_l,highway_fuel_per_100km_l
0,50,Acura,Integra,1 generation,1991,2002,Sedan,1.8 AT,Sedan,1600,370,fwd,Automatic,Inline,4,Gasoline,81.0,89.0,1834,173,5200,144,6300,7.5,205,4,50,8.4,9.4,7.6
1,51,Acura,Integra,1 generation,1991,2002,Sedan,1.8 MT,Sedan,1600,370,fwd,Manual,Inline,4,Gasoline,81.0,89.0,1834,173,5200,144,6300,7.5,205,5,50,8.4,9.4,7.6
2,52,Acura,Integra,1 generation,1991,2002,Sedan,1.8 MT,Sedan,1650,311,fwd,Manual,Inline,4,Gasoline,81.0,87.0,1797,173,6200,172,7600,7.2,210,5,50,8.6,9.4,7.6
3,55,Acura,MDX,1 generation,2001,2006,Crossover,3.5 AT 4WD,Crossover,2580,2308,awd,Automatic,V-type,6,Gasoline,89.0,93.0,3471,332,3000,240,5750,8.7,190,5,73,13.2,13.8,10.2
4,61,Acura,MDX,3 generation,2013,2020,Crossover,3.5 AT 4WD,Crossover,2575,1344,awd,Automatic,V-type,6,Gasoline,89.0,93.0,3471,355,4500,290,6200,7.6,220,6,73,10.4,15.1,7.7

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17077 entries, 0 to 17076
Data columns (total 30 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   id                                   17077 non-null  int64
 1   Make                                 17077 non-null  object
 2   Model                                17077 non-null  object
 3   Generation                           17077 non-null  object
 4   Year_from                            17077 non-null  int64
 5   Year_to                              17077 non-null  int64
 6   Series                               17077 non-null  object
 7   Trim                                 17077 non-null  object
 8   Body_type                            17077 non-null  object
 9   full_weight_kg                       17077 non-null  int64
 10  max_trunk_capacity_l                 17077 non-null  int64
 11  drive_wheels                         17077 non-null  object
 12  transmission                         17077 non-null  object
 13  cylinder_layout                      17077 non-null  object
 14  number_of_cylinders                  17077 non-null  int64
 15  fuel_type                            17077 non-null  object
 16  cylinder_bore_mm                     17077 non-null  float64
 17  stroke_cycle_mm                      17077 non-null  float64
 18  capacity_cm3                         17077 non-null  int64
 19  maximum_torque_n_m                   17077 non-null  int64
 20  turnover_of_maximum_torque_rpm       17077 non-null  int64
 21  engine_hp                            17077 non-null  int64
 22  engine_hp_rpm                        17077 non-null  int64
 23  acceleration_0_100_km/h_s            17077 non-null  float64
 24  max_speed_km_per_h                   17077 non-null  int64
 25  number_of_gears                      17077 non-null  int64
 26  fuel_tank_capacity_l                 17077 non-null  int64
 27  mixed_fuel_consumption_per_100_km_l  17077 non-null  float64
 28  city_fuel_per_100km_l                17077 non-null  float64
 29  highway_fuel_per_100km_l             17077 non-null  float64
dtypes: float64(6), int64(14), object(10)
memory usage: 3.9+ MB

In [ ]:
stats = df.describe()
stats.loc['min_max_mean'] = (stats.loc['min'] + stats.loc['max']) / 2
stats.loc[['min_max_mean']]
stats.loc[['min', 'max', 'min_max_mean']]

,id,Year_from,Year_to,full_weight_kg,max_trunk_capacity_l,number_of_cylinders,cylinder_bore_mm,stroke_cycle_mm,capacity_cm3,maximum_torque_n_m,turnover_of_maximum_torque_rpm,engine_hp,engine_hp_rpm,acceleration_0_100_km/h_s,max_speed_km_per_h,number_of_gears,fuel_tank_capacity_l,mixed_fuel_consumption_per_100_km_l,city_fuel_per_100km_l,highway_fuel_per_100km_l
min,50.0,1964.0,0.0,950.0,72.0,2.0,56.0,55.0,649.0,44.0,1200.0,29.0,1750.0,3.2,100.0,2.0,28.0,2.90,3.6,2.7
max,70904.0,2019.0,2020.0,3966.0,5400.0,12.0,104.0,105.0,6761.0,1020.0,7500.0,710.0,8500.0,33.2,350.0,9.0,159.0,25.60,35.6,18.5
min_max_mean,35477.0,1991.5,1010.0,2458.0,2736.0,7.0,80.0,80.0,3705.0,532.0,4350.0,369.5,5125.0,18.2,225.0,5.5,93.5,14.25,19.6,10.6

In [11]:
df['Body_type'].unique()

array(['Sedan', 'Crossover', 'Coupe', 'Hatchback', 'Liftback', 'Wagon',
       'Cabriolet', 'Roadster', 'Minivan', 'Pickup', 'Fastback', 'Targa'],
      dtype=object)

In [10]:
df['drive_wheels'].unique()

array(['fwd', 'awd', 'rwd', '4wd'], dtype=object)

In [12]:
df['transmission'].unique()

array(['Automatic', 'Manual'], dtype=object)

In [13]:
df['cylinder_layout'].unique()

array(['Inline', 'V-type', 'Opposed', 'W-type', 'Rotary-piston'],
      dtype=object)

In [14]:
df['number_of_cylinders'].unique()

array([ 4,  6,  5,  8, 12,  3, 10,  2], dtype=int64)

In [15]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid', 'Gas'], dtype=object)

In [16]:
df['number_of_gears'].unique()

array([4, 5, 6, 8, 3, 7, 2, 9], dtype=int64)

In [21]:
selected_columns = df[[
    'Year_from',
    'capacity_cm3',
    'engine_hp',
    'maximum_torque_n_m',
    'acceleration_0_100_km/h_s',
    'max_speed_km_per_h',
    'mixed_fuel_consumption_per_100_km_l',
    'city_fuel_per_100km_l',
    'highway_fuel_per_100km_l',
    'max_trunk_capacity_l',
    'full_weight_kg'
]]
selected_columns = selected_columns.rename(columns={
    'Year_from': 'year',
    'capacity_cm3': 'displacement',
    'engine_hp': 'power',
    'maximum_torque_n_m': 'torque',
    'acceleration_0_100_km/h_s': 'acc',
    'max_speed_km_per_h': 'max_speed',
    'mixed_fuel_consumption_per_100_km_l': 'mixed_fc',
    'city_fuel_per_100km_l': 'city_fc',
    'highway_fuel_per_100km_l': 'highway_fc',
    'max_trunk_capacity_l': 'trunk',
    'full_weight_kg': 'weight'
})
selected_columns.head()

,year,displacement,power,torque,acc,max_speed,mixed_fc,city_fc,highway_fc,trunk,weight
0,1991,1834,144,173,7.5,205,8.4,9.4,7.6,370,1600
1,1991,1834,144,173,7.5,205,8.4,9.4,7.6,370,1600
2,1991,1797,172,173,7.2,210,8.6,9.4,7.6,311,1650
3,2001,3471,240,332,8.7,190,13.2,13.8,10.2,2308,2580
4,2013,3471,290,355,7.6,220,10.4,15.1,7.7,1344,2575

In [23]:
selected_columns.to_csv('processed_cars_selected.csv', index=False)